ALTER TABLE crm_helios.company ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE crm_helios.contact ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE crm_helios.deal ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE crm_helios.task ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE crm_helios.user ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;